### ISSUE TITLE
能否做抢票软件，手机版的，有偿

### ISSUE THREAD

**Issue by Charley-liu** [mikumifa/mikumifa#1]

**Comment by mikumifa** [comment]
你要抢啥啊

**Comment by Charley-liu** [comment]
国家博物馆的门票
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月25日 16:56 |
| 收件人 | mikumifa/mikumifa ***@***.***> |
| 抄送人 | Charley ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [mikumifa/mikumifa] 能否做抢票软件，手机版的，有偿 (Issue #1) |

你要抢啥啊
